{
	"salem":  [	 "university", 	"docks", 	"jail",
				 "recruitment",	"court", 	"pharmacy", 
				 "church", 	 	"bar",		"library",
				 "graveyard",	"square", 	"post", 	
		 		"home", 	 	"hospital", "shop"
			] ,
	"ruby":  [	 "university", 	"docks", 	"jail",
				 "recruitment",	"court", 	"pharmacy", 
				 "church", 	 	"bar",		"library",
				 "graveyard",	"square", 	"post", 	
		 		"home", 	 	"hospital", "shop"
			] ,
	"sapphire":  [	 "university", 	"docks", 	"jail",
				 "recruitment",	"court", 	"pharmacy", 
				 "church", 	 	"bar",		"library",
				 "graveyard",	"square", 	"post", 	
		 		"home", 	 	"hospital", "shop"
			] ,
	"barcelona":  ["university", "jail", "church", "graveyard", "square", "post", "bar", "hospital", "home", "court", "recruitment", "shop", "library", "pharmacy", "docks", ""] , 
	"berlin":  ["pharmacy", "jail", "library", "post", "hospital", "home", "university", "recruitment", "graveyard", "", "church", "court", "bar", "square", "docks", "shop"] , 
	"boston":  ["graveyard", "pharmacy", "square", "church", "bar", "home", "docks", "post", "hospital", "shop", "", "recruitment", "jail", "court", "library", "university"] , 
	"charleston":  ["post", "hospital", "docks", "church", "bar", "university", "home", "square", "", "graveyard", "pharmacy", "jail", "shop", "library", "court", "recruitment"] , 
	"chicago":  ["", "bar", "library", "square", "docks", "church", "graveyard", "shop", "post", "university", "recruitment", "hospital", "jail", "court", "home", "pharmacy"] , 
	"delhi":  ["court", "home", "pharmacy", "docks", "university", "", "hospital", "square", "library", "church", "shop", "recruitment", "bar", "graveyard", "jail", "post"] , 
	"dublin":  ["post", "square", "hospital", "court", "university", "docks", "home", "", "shop", "jail", "library", "graveyard", "pharmacy", "church", "bar", "recruitment"] , 
	"edinburg":  ["pharmacy", "docks", "", "bar", "post", "church", "hospital", "university", "home", "recruitment", "court", "shop", "library", "graveyard", "square", "jail"] , 
	"london":  ["recruitment", "graveyard", "library", "square", "jail", "shop", "church", "docks", "court", "", "pharmacy", "university", "hospital", "post", "bar", "home"] , 
	"moscow":  ["graveyard", "pharmacy", "court", "recruitment", "hospital", "library", "docks", "post", "square", "church", "university", "jail", "bar", "home", "", "shop"] , 
	"new britain":  ["bar", "church", "post", "recruitment", "square", "", "home", "library", "graveyard", "hospital", "pharmacy", "shop", "jail", "court", "docks", "university"] , 
	"ny":  ["", "court", "hospital", "pharmacy", "jail", "recruitment", "square", "home", "university", "post", "graveyard", "docks", "church", "bar", "library", "shop"] , 
	"oxford":  ["post", "docks", "recruitment", "library", "home", "hospital", "pharmacy", "square", "shop", "graveyard", "", "church", "university", "jail", "bar", "court"] , 
	"palermo":  ["recruitment", "court", "jail", "docks", "bar", "library", "", "square", "shop", "graveyard", "home", "post", "pharmacy", "university", "hospital", "church"] , 
	"paris":  ["library", "square", "docks", "post", "university", "", "recruitment", "graveyard", "shop", "court", "pharmacy", "home", "hospital", "church", "bar", "jail"] , 
	"prague":  ["church", "pharmacy", "", "docks", "shop", "graveyard", "jail", "home", "square", "court", "hospital", "post", "library", "university", "recruitment", "bar"] , 
	"rome":  ["shop", "university", "pharmacy", "hospital", "recruitment", "jail", "church", "bar", "library", "post", "", "square", "court", "docks", "home", "graveyard"] , 
	"salerno":  ["court", "library", "graveyard", "post", "docks", "university", "", "pharmacy", "shop", "hospital", "jail", "recruitment", "church", "bar", "home", "square"] , 
	"smithston":  ["university", "bar", "court", "library", "shop", "graveyard", "pharmacy", "home", "post", "jail", "recruitment", "church", "", "docks", "square", "hospital"] , 
	"springfield":  ["hospital", "library", "bar", "university", "pharmacy", "recruitment", "church", "home", "graveyard", "square", "docks", "", "jail", "shop", "post", "court"] , 
	"stpetersburg":  ["post", "hospital", "pharmacy", "library", "docks", "court", "church", "jail", "recruitment", "home", "", "square", "bar", "graveyard", "shop", "university"] , 
	"strasburg":  ["bar", "church", "square", "graveyard", "hospital", "jail", "shop", "", "docks", "recruitment", "library", "home", "post", "court", "university", "pharmacy"] , 
	"washington":  ["hospital", "home", "bar", "jail", "recruitment", "square", "pharmacy", "", "library", "docks", "post", "university", "court", "graveyard", "shop", "church"] , 

	"frankfurt": ["bar", "post", "court", "square", "docks", "jail", "home", "library", "shop", "church", "recruitment", "graveyard", "pharmacy", "university", "hospital", ""] , 
	"marginea":  ["docks", "home", "post", "jail", "", "pharmacy", "graveyard", "hospital", "court", "shop", "university", "bar", "recruitment", "square", "church", "library"] , 
	"canterbury":  ["post", "docks", "pharmacy", "graveyard", "church", "", "library", "square", "recruitment", "home", "university", "shop", "bar", "hospital", "jail", "court"] , 
	"baltimor":  ["pharmacy", "square", "bar", "recruitment", "university", "library", "court", "church", "jail", "shop", "docks", "hospital", "post", "graveyard", "home", ""] , 
	"dresden":  ["", "church", "home", "graveyard", "hospital", "court", "docks", "university", "jail", "post", "recruitment", "library", "pharmacy", "shop", "square", "bar"] , 
	"city29":  ["square", "bar", "library", "jail", "shop", "court", "", "university", "graveyard", "docks", "post", "hospital", "church", "recruitment", "pharmacy", "home"] , 
	"city30":  ["shop", "home", "court", "docks", "graveyard", "recruitment", "jail", "church", "", "hospital", "pharmacy", "square", "library", "post", "university", "bar"] , 
	"city31":  ["library", "church", "graveyard", "court", "university", "", "hospital", "square", "jail", "shop", "bar", "pharmacy", "recruitment", "home", "docks", "post"] , 
	"city32":  ["square", "church", "university", "post", "pharmacy", "court", "docks", "hospital", "home", "bar", "", "library", "graveyard", "jail", "shop", "recruitment"] , 
	"city33":  ["library", "home", "graveyard", "bar", "university", "hospital", "post", "", "recruitment", "church", "shop", "jail", "court", "pharmacy", "docks", "square"] , 
	"city34":  ["jail", "library", "post", "church", "graveyard", "court", "square", "recruitment", "pharmacy", "shop", "hospital", "home", "docks", "", "university", "bar"] , 
	"city35":  ["university", "hospital", "jail", "post", "bar", "square", "graveyard", "", "court", "church", "pharmacy", "home", "recruitment", "shop", "docks", "library"] , 
	"city36":  ["docks", "university", "hospital", "", "court", "home", "square", "church", "shop", "pharmacy", "library", "graveyard", "post", "bar", "recruitment", "jail"] , 
	"city37":  ["shop", "jail", "recruitment", "university", "", "pharmacy", "graveyard", "court", "hospital", "post", "docks", "square", "home", "bar", "library", "church"] , 
	"city38":  ["square", "bar", "library", "jail", "court", "recruitment", "graveyard", "docks", "", "university", "church", "home", "shop", "hospital", "post", "pharmacy"] , 
	"city39":  ["recruitment", "", "graveyard", "court", "post", "library", "docks", "home", "pharmacy", "hospital", "bar", "jail", "church", "square", "shop", "university"] , 
	"city40":  ["university", "post", "square", "home", "court", "pharmacy", "church", "recruitment", "", "hospital", "library", "docks", "bar", "shop", "graveyard", "jail"] , 
	"city41":  ["bar", "university", "post", "court", "", "library", "graveyard", "docks", "jail", "pharmacy", "church", "square", "shop", "recruitment", "hospital", "home"] , 
	"city42":  ["court", "bar", "recruitment", "post", "square", "graveyard", "university", "docks", "home", "church", "jail", "library", "pharmacy", "", "hospital", "shop"] , 
	"city43":  ["recruitment", "university", "bar", "shop", "court", "", "home", "post", "jail", "hospital", "library", "church", "square", "pharmacy", "docks", "graveyard"] , 
	"city44":  ["pharmacy", "square", "docks", "hospital", "", "graveyard", "library", "post", "church", "jail", "recruitment", "bar", "home", "university", "shop", "court"] , 
	"city45":  ["hospital", "shop", "court", "university", "pharmacy", "home", "graveyard", "recruitment", "post", "church", "jail", "", "bar", "docks", "library", "square"] , 
	"city46":  ["hospital", "library", "church", "jail", "recruitment", "post", "home", "university", "docks", "graveyard", "bar", "shop", "court", "square", "pharmacy", ""] , 
	"fogtown":  ["graveyard", "university", "bar", "church", "shop", "docks", "square", "library", "jail", "hospital", "recruitment", "court", "", "home", "post", "pharmacy"] , 
	"hartford":  ["", "home", "hospital", "library", "university", "shop", "post", "court", "recruitment", "church", "square", "bar", "graveyard", "pharmacy", "docks", "jail"] , 
	"plymouth":  ["shop", "hospital", "", "university", "home", "court", "bar", "docks", "post", "jail", "pharmacy", "recruitment", "square", "library", "church", "graveyard"] 
}
